name: 'publish npm package'

on:
  push
  # release:
  #   types: [created]

jobs:
  build-and-publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@eSpark'
      - run: npm ci
      - run: npm run prepare
      - run: cat .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
